apiVersion: v1
kind: Service
metadata:
  name: recipe-chatbot-service
spec:
  type: NodePort
  selector:
    app: recipe-chatbot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30007
